name: Deployment 
on:
  push:
    branches:
      - master
     # to ignore some files wich you do not want to trigger the workflow
    paths-ignore: 
      - 'README.md'
      - '.github/workflows/*.yml'    
  workflow_dispatch:
               
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
              
      - name: Install node  js
        uses: actions/setup-node@v4
        with:   
          node-version: '20'
     
          # to cache node modules
      - name: Cache nodemodules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        
      - name: validate version 
        run: node -v
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node  js
        uses: actions/setup-node@v4
        with:   
          node-version: '20'
      - name: validate version 
        run: node -v
      - name: Cache nodemodules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        
      - name: validate version 
        run: node -v
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Archive production artifacts
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist
      - name: deploy files  
        run : echo "deploying successfully" 
      